### PR TITLE
#169393085 fix Ui feature

### PR DESCRIPTION
**Pull request by nraufu**
> #### What does this PR do?
> fix UI bugs
>
> #### Description of Task to be completed
> - align entries center
>- fix colors mixation

> #### How should this be manually tested?
> in the browser small screen simulator . in mozilla firefox press **ctrl+shift+M** to view the simulator

> #### What are the relevant pivotal tracker stories?
>#169393085

### CODE REVIEW

**Comment by NkFab** [comment]
Try to centre those cards and align them one following the other.
image

**Comment by NkFab** [comment]
Make the colour and hover animation on the button consistent across all the pages that have them. 
image
image
Add also a hover animation on links to show that they are clickable links.
image

**Comment by nraufu** [comment]
okay working on it....

**Comment by NkFab** [comment]
The responsiveness on mobile and Ipad pro still has some issues can fix them, please? 
image
image

**Pull request merged**
